---
tiers:
    -
        name: stor4nfv
        order: 2
        description: >-
            Test suite from Stor4NFV project.
        testcases:
            -
                case_name: stor4nfv_k8s
                project_name: stor4nfv
                criteria: 100
                blocking: false
                description: >-
                    This tests are necessary to demonstrate conformance
                    of the K8s+Stor4NFV deployment.
                dependencies:
                    - DEPLOY_SCENARIO: 'stor4nfv'
                run:
                    name: stor4nfv_k8s

    -
        name: clover
        order: 3
        description: >-
            Test suite from Clover project.
        testcases:
            -
                case_name: clover_k8s
                project_name: clover
                criteria: 100
                blocking: false
                description: >-
                    This tests are necessary to demonstrate features
                    of K8s+Istio+Clover deployment.
                dependencies:
                    - DEPLOY_SCENARIO: 'clover'
                run:
                    name: clover_k8s
