---
tiers:
    -
        name: healthcheck
        order: 1
        ci_loop: '(daily)|(weekly)'
        description: >-
            A set of e2e tests integrated from kubernetes project.
        testcases:
            -
                case_name: k8s_smoke
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    Smoke Tests a running Kubernetes cluster, which
                    validates the deployed cluster is accessible, and
                    at least satisfies minimal functional requirements.
                dependencies:
                    installer: '(compass)|(joid)|(kubespray)|(container4nfv)'
                    scenario: 'k8-*'
                run:
                    module: 'functest_kubernetes.k8stest'
                    class: 'K8sSmokeTest'

    -
        name: smoke
        order: 2
        ci_loop: '(daily)|(weekly)'
        description: >-
            A set of conformance tests integrated from kubernetes project.
        testcases:
            -
                case_name: k8s_conformance
                project_name: functest
                criteria: 100
                blocking: false
                description: >-
                    Conformance Tests are expect to pass on any Kubernetes
                    cluster, this tests are necessary demonstrate conformance
                    of the Kubernetes deployment.
                dependencies:
                    installer: '(compass)|(joid)|(kubespray)'
                    scenario: 'k8-*'
                run:
                    module: 'functest_kubernetes.k8stest'
                    class: 'K8sConformanceTest'

    -
        name: stor4nfv
        order: 3
        ci_loop: '(daily)|(weekly)'
        description: >-
            Test suite from Stor4NFV project.
        testcases:
            -
                case_name: stor4nfv_k8s
                project_name: stor4nfv
                criteria: 100
                blocking: false
                description: >-
                    This tests are necessary demonstrate conformance
                    of the K8s+Stor4NFV deployment.
                dependencies:
                    installer: 'compass'
                    scenario: 'stor4nfv'
                run:
                    module: 'stor4nfv_tests.stor4nfv_k8s'
                    class: 'K8sStor4nfvTest'

    -
        name: clover
        order: 4
        ci_loop: '(daily)|(weekly)'
        description: >-
            Test suite from Clover project.
        testcases:
            -
                case_name: clover_k8s
                project_name: clover
                criteria: 100
                blocking: false
                description: >-
                    This tests are necessary demonstrate features
                    of K8s+Istio+Clover deployment.
                dependencies:
                    installer: 'container4nfv'
                    scenario: 'clover'
                run:
                    module: 'clover.functest.clover_k8s'
                    class: 'K8sCloverTest'
