apiVersion: apps/v1
kind: Deployment
metadata:
  name: ellis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ellis
  template:
    metadata:
      labels:
        service: ellis
    spec:
      initContainers:
        - name: wait-on-homestead-prov
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup homestead-prov; do echo waiting for homestead-prov to start ...; sleep 2; done']
        - name: wait-on-sprout
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup sprout; do echo waiting for sprout to start ...; sleep 2; done']
      containers:
      - image: "{{ .Values.image.path }}-ellis:{{ .Values.image.tag }}"
        name: ellis
        ports:
        - containerPort: 22
        - containerPort: 80
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 80
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
