apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: homer
  template:
    metadata:
      labels:
        service: homer
    spec:
      initContainers:
        - name: wait-on-cassandra
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup cassandra; do echo waiting for cassandra to start ...; sleep 2; done']
      containers:
      - image: "{{ .Values.image.path }}-homer:{{ .Values.image.tag }}"
        name: homer
        ports:
        - containerPort: 22
        - containerPort: 7888
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          tcpSocket:
            port: 7888
          initialDelaySeconds: 30
        readinessProbe:
          tcpSocket:
            port: 7888
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
