apiVersion: apps/v1
kind: Deployment
metadata:
  name: homestead-prov
spec:
  replicas: 1
  selector:
    matchLabels:
      service: homestead-prov
  template:
    metadata:
      labels:
        service: homestead-prov
        snmp: enabled
    spec:
      initContainers:
        - name: wait-on-homestead
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup homestead; do echo waiting for homestead to start ...; sleep 2; done']
      containers:
      - image: "{{ .Values.image.path }}-homestead-prov:{{ .Values.image.tag }}"
        name: homestead-prov
        ports:
        - containerPort: 22
        - containerPort: 8889
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/clearwater/bin/poll_homestead-prov.sh"]
          initialDelaySeconds: 60
        readinessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/clearwater/bin/poll_homestead-prov.sh"]
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
