apiVersion: apps/v1
kind: Deployment
metadata:
  name: homestead
spec:
  replicas: 1
  selector:
    matchLabels:
      service: homestead
  template:
    metadata:
      labels:
        service: homestead
        snmp: enabled
    spec:
      initContainers:
        - name: wait-on-cassandra
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup cassandra; do echo waiting for cassandra to start ...; sleep 2; done']
        - name: wait-on-astaire
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup astaire; do echo waiting for astaire to start ...; sleep 2; done']
      containers:
      - image: "{{ .Values.image.path }}-homestead:{{ .Values.image.tag }}"
        name: homestead
        ports:
        - containerPort: 22
        - containerPort: 8888
        envFrom:
        - configMapRef:
              name: env-vars
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "8888"]
          initialDelaySeconds: 60
        readinessProbe:
          exec:
            command: ["/bin/bash", "/usr/share/kubernetes/liveness.sh", "8888"]
        volumeMounts:
        - name: homesteadlogs
          mountPath: /var/log/homestead
      - image: busybox:1.28
        name: tailer
        command: [ "tail", "-F", "/var/log/homestead/homestead_current.txt" ]
        volumeMounts:
        - name: homesteadlogs
          mountPath: /var/log/homestead
      volumes:
      - name: homesteadlogs
        emptyDir: {}
      imagePullSecrets:
      - name: ~
      restartPolicy: Always
